[App]
Name = "Auth"
Address = ":4000"
LogLevel = "debug"

[DB]
PoolMax = 1
URL = "file::memory:?cache=shared"
Driver = "sqliteshim"
PrintQueriesToStdout = true

[Nats]
URL = "tls://connect.ngs.global"
CredentialFile = "./nats.creds"

[Redis]
URL = ".."
EnableTLS = true