# Vscode file
# Works with the "REST Client" extension
# Open this file in vscode and use it with the rest-client extension
# If you dont have the extension installed, please install it

# Examples of using this API
# for vscode users, install `REST Client` to use these example.

### 
# Base URL
@baseUrl = http://localhost:4000

###  Home or Welcome Page - Zample
GET  {{baseUrl}}/zample/ HTTP/1.1 
 
 
###  Example (method not allowed)
POST  {{baseUrl}}/zample HTTP/1.1
Content-Type: application/json


###  Example (url not found, on router level not app level)
GET  {{baseUrl}}/zample/does-not-exist HTTP/1.1
Content-Type: application/json


###   Validation endpoint: here validation done via validation middleware
POST {{baseUrl}}/zample/validation-via-middleware HTTP/1.1
Content-Type: application/json 

{
  "name": "kojjjjjj",
  "phone": "+230",
  "email": "h@d.com"
}


###   Validation endpoint: here validation done in handler
POST {{baseUrl}}/zample/validation-in-handler HTTP/1.1
Content-Type: application/json 

{
  "name": " sdsds      kao",
  "phone": "+230",
  "Age": 2,
  "email": "h@d.com"
}
 


### List using db helpers
GET {{baseUrl}}/zample/list-via-db-helpers HTTP/1.1
Content-Type: application/json


### List using orm in datastore
GET {{baseUrl}}/zample/list-via-repo HTTP/1.1
Content-Type: application/json


### error-500
GET {{baseUrl}}/zample/error-500 HTTP/1.1
Content-Type: application/json

kj body send to log

###  error returned
GET {{baseUrl}}/zample/error-returned HTTP/1.1
Content-Type: application/json


#https://github.com/gmhafiz/go8/blob/master/examples/author.http example